---
- hosts: all
  become: yes
  tasks:
    - name:  install epel-release  
      yum: 
        name: epel-release
        state: present


    - name:  install nginx  
      yum: 
        name: nginx
        state: present
